//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roostersysteem.Models
{
    using System;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using System.Configuration;
    using Roostersysteem.Models;

    public partial class PersoonVak
    {
        //Automatisch gegenereerde properties vanuit de database.
        public Nullable<int> Persoon_Id { get; set; }
        public Nullable<int> Vak_Id { get; set; }
        public int PersoonVak_Id { get; set; }
    
        public virtual Persoon Persoon { get; set; }
        public virtual Vak Vak { get; set; }     
    }
}
